/**
 * Reusable PDF Header, Footer, Signature & Styles
 * Shared across all report generators (attendance, progress card, receipt, timetable, etc.)
 */

import type { SchoolData, SignatureConfig } from './printTypes';

// Transparent 1x1 PNG fallback when no logo is provided
const FALLBACK_LOGO =
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';

/**
 * Report Header
 * Full school header with logo, name, address, contact info, decorative line, title & subtitle.
 * Used as the first-page header; subsequent pages get a simplified version.
 */
export const getReportHeader = (
    schoolData: SchoolData,
    title: string,
    subtitle: string,
    pageOrientation: 'portrait' | 'landscape' = 'portrait',
    asContent: boolean = false
) => {
    // When rendered in header area, side margins are needed (no page margins there).
    // When rendered as content, page margins already handle side spacing.
    const side = asContent ? 0 : 30;
    const lineWidth = pageOrientation === 'landscape' ? 780 : 515;

    return {
        stack: [
            {
                columns: [
                    {
                        width: 70,
                        image: schoolData?.logo || FALLBACK_LOGO,
                        fit: [55, 55],
                    },
                    {
                        width: '*',
                        stack: [
                            {
                                text: schoolData?.schoolName || 'School Name',
                                style: 'schoolName',
                                alignment: 'center',
                            },
                            {
                                text: schoolData?.schoolAddress || 'School Address',
                                style: 'schoolAddress',
                                alignment: 'center',
                            },
                            {
                                text: [
                                    { text: 'Phone: ', bold: true },
                                    schoolData?.schoolPhone || 'N/A',
                                    { text: ' | Email: ', bold: true },
                                    schoolData?.schoolEmail || 'N/A',
                                ],
                                style: 'schoolContact',
                                alignment: 'center',
                            },
                        ],
                    },
                    {
                        width: 70,
                        text: '',
                    },
                ],
                margin: [side, 15, side, 0],
            },
            {
                canvas: [
                    {
                        type: 'line',
                        x1: 0,
                        y1: 3,
                        x2: lineWidth,
                        y2: 3,
                        lineWidth: 2,
                        lineColor: '#667eea',
                    },
                ],
                margin: [side, 3, side, 0],
            },
            {
                text: title,
                style: 'reportTitle',
                margin: [side, 5, side, 2],
            },
            {
                text: subtitle,
                style: 'reportSubtitle',
                margin: [side, 0, side, 5],
            },
        ],
    };
};

/**
 * Report Footer
 * Two rows: main info row + powered-by row.
 */
export const getReportFooter = (
    currentPage: number,
    pageCount: number,
    generatedBy?: string
) => {
    return {
        stack: [
            {
                columns: [
                    {
                        text: `Generated by: ${generatedBy || 'System'}`,
                        fontSize: 8,
                        color: '#666666',
                        alignment: 'left',
                        margin: [40, 0, 0, 0],
                    },
                    {
                        text: `Generated on: ${new Date().toLocaleString('en-IN', {
                            timeZone: 'Asia/Kolkata',
                            year: 'numeric',
                            month: 'short',
                            day: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit',
                        })}`,
                        fontSize: 8,
                        color: '#666666',
                        alignment: 'center',
                    },
                    {
                        text: `Page ${currentPage} of ${pageCount}`,
                        fontSize: 8,
                        color: '#666666',
                        alignment: 'right',
                        margin: [0, 0, 40, 0],
                    },
                ],
            },
            {
                text: 'Powered by Klopterz Technologies',
                fontSize: 7,
                color: '#999999',
                alignment: 'center',
                margin: [0, 4, 0, 0],
            },
        ],
        margin: [0, 8, 0, 5],
    };
};

/**
 * Signature Section
 * Renders signature lines with labels (default: Class Teacher + Principal).
 * Customizable via the `signatures` parameter.
 */
export const getSignatureSection = (signatures: SignatureConfig[] = []) => {
    const defaultSignatures: SignatureConfig[] = [
        { label: 'Class Teacher Signature', position: 'left' },
        { label: 'Principal Signature', position: 'right' },
    ];

    const sigs = signatures.length > 0 ? signatures : defaultSignatures;
    const columns: any[] = [];

    sigs.forEach((sig, index) => {
        const alignment =
            sig.position === 'left' ? 'left' : sig.position === 'right' ? 'right' : 'center';

        columns.push({
            width: '*',
            stack: [
                { text: '\n\n\n', fontSize: 8 },
                {
                    canvas: [{ type: 'line', x1: 0, y1: 0, x2: 120, y2: 0, lineWidth: 1 }],
                    alignment,
                },
                { text: sig.label, fontSize: 9, margin: [0, 5, 0, 0], alignment },
            ],
        });

        // Add spacer between signatures
        if (index < sigs.length - 1) {
            columns.push({ width: '*', text: '' });
        }
    });

    return {
        columns,
        margin: [0, 30, 0, 0],
    };
};

/**
 * Common PDF Styles
 * Shared across all report document definitions.
 */
export const commonPdfStyles = {
    schoolName: {
        fontSize: 18,
        bold: true,
        color: '#667eea',
        margin: [0, 5, 0, 2],
    },
    schoolAddress: {
        fontSize: 10,
        color: '#666666',
        margin: [0, 2, 0, 2],
    },
    schoolContact: {
        fontSize: 9,
        color: '#666666',
        margin: [0, 2, 0, 5],
    },
    reportTitle: {
        fontSize: 16,
        bold: true,
        alignment: 'center',
        color: '#667eea',
    },
    reportSubtitle: {
        fontSize: 10,
        alignment: 'center',
        color: '#666666',
        lineHeight: 1.2,
    },
    tableHeader: {
        fontSize: 10,
        bold: true,
        alignment: 'left',
        color: '#ffffff',
        fillColor: '#667eea',
    },
    tableHeaderSmall: {
        fontSize: 8,
        bold: true,
        alignment: 'left',
    },
    sectionTitle: {
        fontSize: 12,
        bold: true,
        color: '#667eea',
        margin: [0, 10, 0, 5],
    },
    section: {
        margin: [0, 5, 0, 5],
    },
};

/**
 * Format date to "DD MMM YYYY" (e.g. "15 Feb 2026")
 */
export const formatDate = (dateString: string): string => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
    });
};

/**
 * Format date short - day only (e.g. "15")
 */
export const formatDateShort = (dateString: string): string => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-IN', {
        day: '2-digit',
    });
};

/**
 * Load pdfmake fonts (call once before generating any PDF)
 */
let fontsLoaded = false;

export const loadPdfFonts = async (): Promise<void> => {
    if (fontsLoaded) return;
    try {
        const pdfFontsModule = await import('pdfmake/build/vfs_fonts');
        const pdfMake = (await import('pdfmake/build/pdfmake')).default;

        if (pdfFontsModule.default && (pdfFontsModule.default as any).pdfMake) {
            pdfMake.vfs = (pdfFontsModule.default as any).pdfMake.vfs;
        } else if ((pdfFontsModule as any).pdfMake) {
            pdfMake.vfs = (pdfFontsModule as any).pdfMake.vfs;
        } else if (pdfFontsModule.default) {
            pdfMake.vfs = pdfFontsModule.default as any;
        } else {
            pdfMake.vfs = pdfFontsModule as any;
        }
        fontsLoaded = true;
    } catch (error) {
        console.warn('Could not load pdfmake fonts:', error);
    }
};
